### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by scmanjarrez** [LoL-Fantome/LeagueToolkit#107]
Hi, I'm trying to fix an error in lol2gltf executable, but it's crashing trying to load the animations when using Fantome library.

I'm trying to load [this animation](https://drive.google.com/file/d/1BJfG3krKTfIo0nBwmTVvzYB_Gzkuz-4d/view?usp=sharing) but it's crashing with this output. Here are the [skl ](https://drive.google.com/file/d/1SsABuhw-dDvfGnu9kiWfo0KUiR-CyydQ/view?usp=sharing)and [skn](https://drive.google.com/file/d/1EvcUWQPg80RoxTmz1DiR2mchUbxezE7o/view?usp=sharing) file just in case.
```
System.ArgumentException: An item with the same key has already been added. Key: 219888547
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Fantome.Libraries.League.IO.AnimationFile.Animation.ReadCompressed(BinaryReader br)
   at Fantome.Libraries.League.IO.AnimationFile.Animation..ctor(Stream stream)
   at Fantome.Libraries.League.IO.AnimationFile.Animation..ctor(String fileLocation)
```

**Comment by Crauzer** [comment]
#108
